version: "3.7"

services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports: 
      - '5433:5432'
    volumes:
      - app-postgres:/var/lib/postgresql/data

  app:
    build: .
    links: 
      - postgres
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123456

volumes: 
  app-postgres: